remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Netnerd Network]
tagline: [This is the personal blog of Kevin McLeod]
description: [A personal blog on How-to for all things Computer and Computer Network related]
